name: exchangerates
description: A new Flutter application.

version: 0.0.2+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  flutter_money_formatter: ^0.8.3
  flag: ^1.0.3
  intl: ^0.15.8
  firebase_admob: ^0.9.3+2
  url_launcher: ^5.4.5
  device_info: ^0.4.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
